version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/cartTest:
          requires:
            - cypress/install
          store_artifacts: true
          parallel: true
          parallelism: 1
          group: "machine-1" # Grupa dla pierwszej maszyny
      - cypress/loginTest:
          requires:
            - cypress/install
          store_artifacts: true
          parallel: true
          parallelism: 1
          group: "machine-2" # Grupa dla drugiej maszyny

