version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          store_artifacts: true
          spec: cypress/e2e/cartPageTest.cy.js
      - cypress/run:
          requires:
            - cypress/install
          store_artifacts: true
          spec: cypress/e2e/logInPageTest.cy.js
      - cypress/run:
          requires:
            - cypress/install
          store_artifacts: true
          spec: cypress/e2e/orderPageTest.cy.js
      - cypress/run:
          requires:
            - cypress/install
          store_artifacts: true
          spec: cypress/e2e/productPageTest.cy.js
      - cypress/run:
          requires:
            - cypress/install
          store_artifacts: true
          spec: cypress/e2e/myAccountPageTest.cy.js
